<?php
	
	// ECHO MOSTRA MENSAGEM NA TELA
	
	
	echo "<pre>"; //ORGANIZA OS ELEMENTOS DO ARRAY PARA EXIBIÇÃO

	// PRINT R MOSTRA AS VARIÁVEIS EM UM ARRAY
	print_r($_SERVER);
	
	echo "</pre><BR><BR>";

	// PRINT R MOSTRA AS VARIÁVEIS EM UM ARRAY
	print_r($_SERVER);
	
?>